sudo: required
env:
  - npm_registry=https://registry.npmjs.com
services:
  - mongodb
language: node_js
node_js:
  - '5'
  - '4'
install:
  - npm i npminstall
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
